language: python
install:
  - pip install .
  - pip install coveralls pytest pytest-cov
script:
  - py.test --doctest-modules collection.py README.rst
after_success:
  - coveralls
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: nightly
  fast_finish: true
